
CREATE TABLE IF NOT EXISTS tasks (
  id         INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title      VARCHAR(255)  NOT NULL,
  completed  TINYINT(1)    NOT NULL DEFAULT 0,
  created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
